name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: benchengfeng/NomadMee@v4
        with:
          ref: main

      - name: Install backend PHP dependencies with Composer
        run: |
          cd backend
          composer install --no-dev --optimize-autoloader

      - name: Deploy to Production
        run: |
          rsync -av --delete ./backend/* ../www/nomadmee/backend

