name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: benchengfeng/NomadMee@v4
        with:
          ref: main

      - name: Install dependencies and build
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy to Production
        run: |
          rsync -av --delete ./client/build/* ../www/nomadmee
          rsync -av --delete ./client/public ../www/nomadmee
          rsync -av --delete ./backend/* ../www/nomadmee/backend

