name: Build and Deploy prod

on:
  push:
    branches:
      - main
      - v1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install dependencies and build
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy to Production
        run: |
          rsync -av --delete ./client/build/* ../www
          rsync -av --delete ./client/public ../www
