on:
  push:
    branches:
      - main
      - v1

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy to Alibaba Cloud ECS
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 🔑 Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.ECS_SSH_PRIVATE_KEY }}

    - name: 📂 Deploy client files to ECS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.ECS_USERNAME }}@${{ secrets.ECS_IP }} "mkdir -p /var/www/NomadMee/client/build"
        scp -r client/build/* ${{ secrets.ECS_USERNAME }}@${{ secrets.ECS_IP }}:/var/www/NomadMee/client/build

    - name: 📂 Deploy backend files to ECS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.ECS_USERNAME }}@${{ secrets.ECS_IP }} "mkdir -p /www/NomadMee/backend"
        scp -r backend/* ${{ secrets.ECS_USERNAME }}@${{ secrets.ECS_IP }}:/www/NomadMee/backend
